name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Build APK
        run: ./gradlew app:assembleRelease

      - name: Sign APK
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEY }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          echo "${KEYSTORE}" | base64 -d > apksign.keystore
          ${ANDROID_HOME}/build-tools/34.0.0/apksigner sign --ks apksign.keystore --ks-pass env:SIGNING_STORE_PASSWORD "app/build/outputs/apk/release/app-release-unsigned.apk"

      - name: Create release
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          gzip: folders
          files: NotiFlow-app-release.apk:app/build/outputs/apk/release/app-release-unsigned.apk
